// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function PauseProcess(arg1) {
  return window['go']['main']['App']['PauseProcess'](arg1);
}

export function ResumeProcess(arg1) {
  return window['go']['main']['App']['ResumeProcess'](arg1);
}
