// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcess(arg1:string):Promise<void>;

export function ListProcesses():Promise<Array<string>>;

export function PauseProcess(arg1:string):Promise<void>;

export function ResumeProcess(arg1:string):Promise<void>;
